// LLM Provider types
export type LLMProvider = 'openai' | 'anthropic';

// Sync status for repositories
export type SyncStatus = 'pending' | 'syncing' | 'synced' | 'error';

// Platform types
export type Platform = 'web' | 'mobile';

// Quality rating for AI-generated questions
export type QualityRating = -2 | -1 | 0 | 1 | 2;

// User profile (stored in public.users table)
export interface User {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
  createdAt: string;
  updatedAt: string;
}

// Authentication state for the application
export type AuthState =
  | 'loading'      // Initial load, checking session
  | 'logged_out'   // No session, need to login
  | 'ready';       // Logged in, ready to use

// Authenticated user (from Supabase auth)
export interface AuthUser {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
}

// Repository (stored in public.repositories table)
export interface Repository {
  id: string;
  userId: string;
  url: string;
  name: string;
  description?: string;
  isPrivate: boolean;
  docoraRepositoryId?: string;  // Phase 11: Docora integration
  lumioignoreContent?: string;  // Content of .lumioignore file for filtering cards
  formatVersion: number;
  syncStatus: SyncStatus;
  syncErrorMessage?: string;
  createdAt: string;
  updatedAt: string;
}

// Card (stored in public.cards table)
export interface Card {
  id: string;
  repositoryId: string;
  filePath: string;
  contentHash: string;
  rawContent: string;  // Original file content (complete markdown with frontmatter)
  title: string;
  content: string;     // Parsed markdown body (without frontmatter)
  tags: string[];
  difficulty: number;
  language: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Card asset (stored in public.card_assets table)
// Maps original image paths in markdown to Supabase Storage paths
export interface CardAsset {
  id: string;
  cardId: string;
  originalPath: string;   // Original path in markdown (e.g., /assets/img/diagram.png)
  storagePath: string;    // Path in Supabase Storage (e.g., user_id/repo_id/hash.png)
  contentHash: string;    // SHA-256 of image content for deduplication
  mimeType: string;       // e.g., image/png, image/jpeg
  sizeBytes?: number;     // File size in bytes
  createdAt: string;
}

// Card frontmatter from markdown parsing
export interface CardFrontmatter {
  title: string;
  tags: string[];
  difficulty?: number;
  language?: string;
}

// README frontmatter for deck validation
export interface DeckFrontmatter {
  lumio_format_version: number;
  description: string;
}

// User stats for dashboard
export interface UserStats {
  repositoryCount: number;
  cardCount: number;
}

// =============================================================================
// REPOSITORY TYPES (Phase 9)
// =============================================================================

// Options for adding a repository
export interface AddRepositoryOptions {
  url: string;
  isPrivate?: boolean;
  accessToken?: string;  // Required for private repos, passed to Docora (not stored)
}

// =============================================================================
// PLATFORM CONFIG (Phase 10)
// =============================================================================

// Platform-level AI configuration (stored in public.platform_config table)
export interface PlatformConfig {
  provider: LLMProvider;
  model: string;
  systemPrompt: string;
}

// =============================================================================
// STUDY TYPES (Phase 4)
// =============================================================================

// Quiz question generated by AI
export interface QuizQuestion {
  question: string;
  options: {
    label: string; // A, B, C, D
    text: string;
  }[];
  correctAnswer: string; // A, B, C, or D
  explanation: string;
}

// Quiz response from llm-proxy
export interface QuizResponse {
  success: boolean;
  quiz?: QuizQuestion;
  error?: string;
}

// Validation response from AI (Step 2)
export interface ValidationResponse {
  isCorrect: boolean;
  explanation: string;
  tips?: string[];
}
