// LLM Provider types
export type LLMProvider = 'openai' | 'anthropic';

// Sync status for repositories
export type SyncStatus = 'pending' | 'syncing' | 'synced' | 'error' | 'failed';

// Platform types
export type Platform = 'web' | 'mobile';

// Quality rating for AI-generated questions
export type QualityRating = -2 | -1 | 0 | 1 | 2;

// User profile (stored in public.users table)
export interface User {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
  createdAt: string;
  updatedAt: string;
}

// Authentication state for the application
export type AuthState =
  | 'loading'      // Initial load, checking session
  | 'logged_out'   // No session, need to login
  | 'ready';       // Logged in, ready to use

// Authenticated user (from Supabase auth)
export interface AuthUser {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
}

/**
 * Repository condiviso tra utenti (stored in public.repositories table).
 * Ogni URL esiste una sola volta nel sistema.
 * Gli utenti sono collegati tramite UserRepository.
 */
export interface Repository {
  id: string;
  // userId rimosso - repository ora condivisi tra utenti (vedi UserRepository)
  url: string;
  name: string;
  description?: string;
  isPrivate: boolean;
  docoraRepositoryId?: string;  // Phase 11: Docora integration
  lumioignoreContent?: string;  // Content of .lumioignore file for filtering cards
  formatVersion: number;
  syncStatus: SyncStatus;
  syncErrorMessage?: string;
  syncErrorType?: string;
  isAuthError: boolean;
  syncFailedAt?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Relazione many-to-many tra utenti e repository (stored in public.user_repositories table).
 * Permette a più utenti di condividere lo stesso repository.
 */
export interface UserRepository {
  id: string;
  userId: string;
  repositoryId: string;
  createdAt: string;
}

// Card (stored in public.cards table)
export interface Card {
  id: string;
  repositoryId: string;
  filePath: string;
  contentHash: string;
  rawContent: string;  // Original file content (complete markdown with frontmatter)
  title: string;
  content: string;     // Parsed markdown body (without frontmatter)
  tags: string[];
  difficulty: number;
  language: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Card asset (stored in public.card_assets table)
// Maps original image paths in markdown to Supabase Storage paths
export interface CardAsset {
  id: string;
  cardId: string;
  originalPath: string;   // Original path in markdown (e.g., /assets/img/diagram.png)
  storagePath: string;    // Path in Supabase Storage (e.g., repo_id/assets/img/diagram.png)
  contentHash: string;    // SHA-256 of image content for deduplication
  mimeType: string;       // e.g., image/png, image/jpeg
  sizeBytes?: number;     // File size in bytes
  createdAt: string;
}

// Card frontmatter from markdown parsing
export interface CardFrontmatter {
  title: string;
  tags: string[];
  difficulty?: number;
  language?: string;
}

// README frontmatter for deck validation
export interface DeckFrontmatter {
  lumio_format_version: number;
  description: string;
}

// User stats for dashboard
export interface UserStats {
  repositoryCount: number;
  cardCount: number;
}

// =============================================================================
// REPOSITORY TYPES (Phase 9)
// =============================================================================

// Options for adding a repository
export interface AddRepositoryOptions {
  url: string;
  isPrivate?: boolean;
  accessToken?: string;  // Required for private repos, passed to Docora (not stored)
}

// =============================================================================
// PLATFORM CONFIG (Phase 10)
// =============================================================================

// Platform-level AI configuration (stored in public.platform_config table)
export interface PlatformConfig {
  provider: LLMProvider;
  model: string;
  systemPrompt: string;
}

// =============================================================================
// STUDY TYPES (Phase 4)
// =============================================================================

// Quiz question generated by AI
export interface QuizQuestion {
  question: string;
  options: {
    label: string; // A, B, C, D
    text: string;
  }[];
  correctAnswer: string; // A, B, C, or D
  explanation: string;
}

// Quiz response from llm-proxy
export interface QuizResponse {
  success: boolean;
  quiz?: QuizQuestion;
  error?: string;
}

// Validation response from AI (Step 2)
export interface ValidationResponse {
  isCorrect: boolean;
  explanation: string;
  tips?: string[];
}

// =============================================================================
// PRE-GENERATED QUESTIONS (Milestone 12 - Batch Mode)
// =============================================================================

// Option in a quiz question
export interface QuizOption {
  label: string; // A, B, C, D
  text: string;
}

// Pre-generated question stored in card_questions table
export interface CardQuestion {
  id: string;
  cardId: string;
  questionText: string;
  options: QuizOption[];
  correctAnswer: string; // A, B, C, D
  explanation: string;   // Pre-generated
  llmProvider: LLMProvider;
  llmModel: string;
  generatedAt: string;
  upvotes: number;
  downvotes: number;
  voteScore: number;
  isActive: boolean;
  deactivatedAt?: string;
  deactivationReason?: 'vote_threshold' | 'manual' | 'card_updated';
  createdAt: string;
  updatedAt: string;
}

// Question with shuffled options for display (from get_question action)
export interface ShuffledQuestion {
  questionId: string;
  question: string;
  options: QuizOption[];  // Options already shuffled
  correctAnswer: string;  // Label after shuffle (A, B, C, D)
  explanation: string;    // Pre-generated explanation
  voteScore: number;
}

// Response from get_question action
export interface GetQuestionResponse {
  success: boolean;
  question: ShuffledQuestion | null;
  fallbackRequired: boolean;
  error?: string;
}

// Vote on a question
export type QuestionVote = 'like' | 'dislike';

// Request to vote on a question
export interface VoteQuestionRequest {
  questionId: string;
  vote: QuestionVote;
}

// Response from vote_question action
export interface VoteQuestionResponse {
  success: boolean;
  voteId?: string;
  currentVoteScore?: number;
  error?: string;
}

// User's vote on a question
export interface QuestionUserVote {
  id: string;
  questionId: string;
  userId: string;
  voteValue: -1 | 1;
  createdAt: string;
}

// Card with question count (for study filtering)
export interface StudyCard extends Card {
  questionCount: number;
}

// =============================================================================
// STUDY SESSIONS (Phase 15 - Study Stats)
// =============================================================================

// Completed study session (stored in public.study_sessions table)
export interface StudySession {
  id: string;
  userId: string;
  repositoryName: string | null;  // null = all repositories
  correctCount: number;
  totalCount: number;
  skippedCount: number;
  durationSeconds: number;
  completedAt: string;
  createdAt: string;
}

// Options for saving a study session
export interface SaveStudySessionOptions {
  repositoryName?: string | null;
  correctCount: number;
  totalCount: number;
  skippedCount: number;
  durationSeconds: number;
}
