// LLM Provider types
export type LLMProvider = 'openai' | 'anthropic';

// Sync status for repositories
export type SyncStatus = 'pending' | 'syncing' | 'synced' | 'error';

// Token status for private repositories (Phase 9)
export type TokenStatus = 'valid' | 'invalid' | 'not_required';

// Platform types
export type Platform = 'web' | 'mobile';

// Quality rating for AI-generated questions
export type QualityRating = -2 | -1 | 0 | 1 | 2;

// User profile (stored in public.users table)
export interface User {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
  createdAt: string;
  updatedAt: string;
}

// User API Key (stored in public.user_api_keys table)
export interface UserApiKey {
  id: string;
  userId: string;
  provider: LLMProvider;
  isValid: boolean;
  isPreferred: boolean;
  lastTestedAt?: string;
  createdAt: string;
  updatedAt: string;
}

// Authentication state for the application
// Note: 'needs_api_key' removed in Phase 6 - user goes directly to dashboard
export type AuthState =
  | 'loading'      // Initial load, checking session
  | 'logged_out'   // No session, need to login
  | 'ready';       // Logged in, ready to use (API key check is informational only)

// Authenticated user (from Supabase auth)
export interface AuthUser {
  id: string;
  email: string;
  displayName?: string;
  avatarUrl?: string;
}

// Repository (stored in public.repositories table)
export interface Repository {
  id: string;
  userId: string;
  url: string;
  name: string;
  description?: string;
  isPrivate: boolean;
  tokenStatus: TokenStatus;  // Phase 9: validity of access token
  tokenErrorMessage?: string;  // Phase 9: error message if token is invalid
  formatVersion: number;
  lastCommitSha?: string;
  lastSyncedAt?: string;
  syncStatus: SyncStatus;
  syncErrorMessage?: string;
  cardCount: number;
  createdAt: string;
  updatedAt: string;
}

// Card (stored in public.cards table)
export interface Card {
  id: string;
  repositoryId: string;
  filePath: string;
  contentHash: string;
  rawContent: string;  // Original file content (complete markdown with frontmatter)
  title: string;
  content: string;     // Parsed markdown body (without frontmatter)
  tags: string[];
  difficulty: number;
  language: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Card asset (stored in public.card_assets table)
// Maps original image paths in markdown to Supabase Storage paths
export interface CardAsset {
  id: string;
  cardId: string;
  originalPath: string;   // Original path in markdown (e.g., /assets/img/diagram.png)
  storagePath: string;    // Path in Supabase Storage (e.g., user_id/repo_id/hash.png)
  contentHash: string;    // SHA-256 of image content for deduplication
  mimeType: string;       // e.g., image/png, image/jpeg
  sizeBytes?: number;     // File size in bytes
  createdAt: string;
}

// Card frontmatter from markdown parsing
export interface CardFrontmatter {
  title: string;
  tags: string[];
  difficulty?: number;
  language?: string;
}

// README frontmatter for deck validation
export interface DeckFrontmatter {
  lumio_format_version: number;
  description: string;
}

// User stats for dashboard
export interface UserStats {
  repositoryCount: number;
  cardCount: number;
}

// =============================================================================
// REPOSITORY TYPES (Phase 9)
// =============================================================================

// Options for adding a repository
export interface AddRepositoryOptions {
  url: string;
  isPrivate?: boolean;
  accessToken?: string;  // Required if isPrivate is true
}

// Response from token validation
export interface TokenValidationResult {
  valid: boolean;
  repoName?: string;
  error?: string;
}

// =============================================================================
// STUDY TYPES (Phase 4)
// =============================================================================

// LLM Model for study session
export interface LLMModel {
  provider: LLMProvider;
  modelId: string;
  displayName: string;
}

// Available models per provider (Phase 5 - only latest models)
export const AVAILABLE_MODELS: Record<LLMProvider, LLMModel[]> = {
  openai: [
    { provider: 'openai', modelId: 'gpt-4o', displayName: 'GPT-4o' },
    { provider: 'openai', modelId: 'o1', displayName: 'o1' },
  ],
  anthropic: [
    { provider: 'anthropic', modelId: 'claude-3-5-haiku-latest', displayName: 'Claude 3.5 Haiku' },
    { provider: 'anthropic', modelId: 'claude-sonnet-4-20250514', displayName: 'Claude Sonnet 4' },
    { provider: 'anthropic', modelId: 'claude-opus-4-20250514', displayName: 'Claude Opus 4' },
  ],
};

// Quiz question generated by AI
export interface QuizQuestion {
  question: string;
  options: {
    label: string; // A, B, C, D
    text: string;
  }[];
  correctAnswer: string; // A, B, C, or D
  explanation: string;
}

// Quiz response from llm-proxy
export interface QuizResponse {
  success: boolean;
  quiz?: QuizQuestion;
  error?: string;
}

// Available models response from llm-proxy
export interface AvailableModelsResponse {
  success: boolean;
  providers: {
    provider: LLMProvider;
    models: LLMModel[];
    isConfigured: boolean;
  }[];
}

// Study preferences
export interface StudyPreferences {
  systemPrompt: string;
  isCustom: boolean;
  preferredProvider?: LLMProvider;
  preferredModel?: string;
}

// Validation response from AI (Step 2)
export interface ValidationResponse {
  isCorrect: boolean;
  explanation: string;
  tips?: string[];
}
