// Auto-generated by scripts/extract-version.cjs from .planning/STATE.md -- do not edit manually
/**
 * Lumio Version - Single Source of Truth
 *
 * This file is generated at build time by scripts/extract-version.cjs.
 * The version is extracted from .planning/STATE.md Milestone field.
 */
export const VERSION = "1.7";

/**
 * Build info populated at build time by CI.
 * In local development, uses default fallback values.
 */
export const BUILD_INFO = {
  version: VERSION,
  buildNumber: process.env.BUILD_NUMBER || "dev",
  gitSha: process.env.COMMIT_SHA || process.env.GIT_SHA || "local",
  buildDate: process.env.BUILD_DATE || new Date().toISOString(),
} as const;

export type BuildInfo = typeof BUILD_INFO;

/**
 * Formatted version string for display
 */
export function getVersionString(): string {
  return `v${BUILD_INFO.version}`;
}

/**
 * Full version string for debug
 */
export function getFullVersionString(): string {
  return `v${BUILD_INFO.version} (${BUILD_INFO.buildNumber}-${BUILD_INFO.gitSha.slice(0, 7)})`;
}

/**
 * Display version with build reference for app UI
 * Format: v1.7+42.abc1234 (CI) or v1.7+dev (local)
 */
export function getDisplayVersion(): string {
  if (BUILD_INFO.buildNumber === "dev") {
    return `v${BUILD_INFO.version}+dev`;
  }
  return `v${BUILD_INFO.version}+${BUILD_INFO.buildNumber}.${BUILD_INFO.gitSha.slice(0, 7)}`;
}
