// Auto-generated by scripts/extract-version.cjs from .planning/STATE.md -- do not edit manually
/**
 * Lumio Version - Single Source of Truth
 *
 * This file is generated at build time by scripts/extract-version.cjs.
 * The version is extracted from .planning/STATE.md Milestone field.
 * Build metadata is baked in as string literals (React Native has no process.env).
 */
export const VERSION = "2.1";

/**
 * Build info baked in at generation time.
 * CI sets BUILD_NUMBER, GIT_SHA, BUILD_DATE env vars before running this script.
 * Local dev gets fallback values: "dev", "local", current timestamp.
 */
export const BUILD_INFO: {
  readonly version: string;
  readonly buildNumber: string;
  readonly gitSha: string;
  readonly buildDate: string;
} = {
  version: VERSION,
  buildNumber: "dev",
  gitSha: "local",
  buildDate: "2026-03-04T15:48:08.661Z",
};

export type BuildInfo = typeof BUILD_INFO;

/**
 * Formatted version string for display
 */
export function getVersionString(): string {
  return `v${BUILD_INFO.version}`;
}

/**
 * Full version string for debug
 */
export function getFullVersionString(): string {
  return `v${BUILD_INFO.version} (${BUILD_INFO.buildNumber}-${BUILD_INFO.gitSha.slice(0, 7)})`;
}

/**
 * Display version with build reference for app UI
 * Format: v1.7+42.abc1234 (CI) or v1.7+dev (local)
 */
export function getDisplayVersion(): string {
  if (BUILD_INFO.buildNumber === "dev") {
    return `v${BUILD_INFO.version}+dev`;
  }
  return `v${BUILD_INFO.version}+${BUILD_INFO.buildNumber}.${BUILD_INFO.gitSha.slice(0, 7)}`;
}
