/**
 * Extract version from .planning/STATE.md and generate packages/shared/src/version.ts
 *
 * Usage: node scripts/extract-version.cjs
 *
 * - Reads the Milestone field from .planning/STATE.md
 * - Writes packages/shared/src/version.ts with the extracted version
 * - Prints the version to stdout (for CI to capture)
 *
 * Exit codes:
 *   0 = success
 *   1 = STATE.md not found or no Milestone field
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const STATE_PATH = path.join(ROOT, ".planning", "STATE.md");
const VERSION_TS_PATH = path.join(
  ROOT,
  "packages",
  "shared",
  "src",
  "version.ts"
);

// 1. Read STATE.md
if (!fs.existsSync(STATE_PATH)) {
  process.stderr.write(`ERROR: STATE.md not found at ${STATE_PATH}\n`);
  process.exit(1);
}

const stateContent = fs.readFileSync(STATE_PATH, "utf-8");

// 2. Parse Milestone field
const match = stateContent.match(/^Milestone:\s*v?([\d.]+)/m);

if (!match) {
  process.stderr.write(
    'ERROR: No "Milestone: vX.Y" line found in STATE.md\n'
  );
  process.exit(1);
}

const version = match[1];

// 3. Generate version.ts
const versionTs = `// Auto-generated by scripts/extract-version.cjs from .planning/STATE.md -- do not edit manually
/**
 * Lumio Version - Single Source of Truth
 *
 * This file is generated at build time by scripts/extract-version.cjs.
 * The version is extracted from .planning/STATE.md Milestone field.
 */
export const VERSION = "${version}";

/**
 * Build info populated at build time by CI.
 * In local development, uses default fallback values.
 */
export const BUILD_INFO = {
  version: VERSION,
  buildNumber: process.env.BUILD_NUMBER || "dev",
  gitSha: process.env.COMMIT_SHA || process.env.GIT_SHA || "local",
  buildDate: process.env.BUILD_DATE || new Date().toISOString(),
} as const;

export type BuildInfo = typeof BUILD_INFO;

/**
 * Formatted version string for display
 */
export function getVersionString(): string {
  return \`v\${BUILD_INFO.version}\`;
}

/**
 * Full version string for debug
 */
export function getFullVersionString(): string {
  return \`v\${BUILD_INFO.version} (\${BUILD_INFO.buildNumber}-\${BUILD_INFO.gitSha.slice(0, 7)})\`;
}
`;

fs.writeFileSync(VERSION_TS_PATH, versionTs, "utf-8");

// 4. Print version to stdout
console.log(version);
