/**
 * Extract version from .planning/STATE.md and generate packages/shared/src/version.ts
 *
 * Usage: node scripts/extract-version.cjs
 *
 * - Reads the Milestone field from .planning/STATE.md
 * - If GIT_TAG env var is set and contains a higher version, uses that instead
 * - Writes packages/shared/src/version.ts with the extracted version
 * - Prints the version to stdout (for CI to capture)
 *
 * Exit codes:
 *   0 = success
 *   1 = STATE.md not found or no Milestone field
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const STATE_PATH = path.join(ROOT, ".planning", "STATE.md");
const VERSION_TS_PATH = path.join(
  ROOT,
  "packages",
  "shared",
  "src",
  "version.ts"
);
const PACKAGE_JSON_PATH = path.join(ROOT, "package.json");

// 1. Read STATE.md
if (!fs.existsSync(STATE_PATH)) {
  process.stderr.write(`ERROR: STATE.md not found at ${STATE_PATH}\n`);
  process.exit(1);
}

const stateContent = fs.readFileSync(STATE_PATH, "utf-8");

// 2. Parse Milestone field
const match = stateContent.match(/^Milestone:\s*v?([\d.]+)/m);

if (!match) {
  process.stderr.write(
    'ERROR: No "Milestone: vX.Y" line found in STATE.md\n'
  );
  process.exit(1);
}

let version = match[1];

// 2b. Compare with GIT_TAG if set (CI passes github.ref_name)
/**
 * Compare two version strings segment by segment.
 * Handles 2-segment (1.7) and 3-segment (2.1.1) versions.
 * Returns -1 if a < b, 0 if a == b, 1 if a > b.
 */
function compareVersions(a, b) {
  const partsA = a.split(".").map(Number);
  const partsB = b.split(".").map(Number);
  const len = Math.max(partsA.length, partsB.length);
  for (let i = 0; i < len; i++) {
    const segA = partsA[i] || 0;
    const segB = partsB[i] || 0;
    if (segA < segB) return -1;
    if (segA > segB) return 1;
  }
  return 0;
}

const gitTag = process.env.GIT_TAG;
if (gitTag) {
  const tagMatch = gitTag.match(/^v?(\d+\.\d+(?:\.\d+)?)$/);
  if (tagMatch) {
    const tagVersion = tagMatch[1];
    if (compareVersions(tagVersion, version) > 0) {
      process.stderr.write(
        `VERSION: Using git tag v${tagVersion} (higher than STATE.md v${version})\n`
      );
      version = tagVersion;
    } else {
      process.stderr.write(
        `VERSION: Using STATE.md v${version} (git tag v${tagVersion} is not higher)\n`
      );
    }
  }
}

// 3. Read build metadata from env vars (set by CI) or use dev fallbacks
const buildNumber = process.env.BUILD_NUMBER || "dev";
const gitSha = process.env.COMMIT_SHA || process.env.GIT_SHA || "local";
const buildDate = process.env.BUILD_DATE || new Date().toISOString();

// 4. Generate version.ts with hardcoded string literals (not process.env references)
// React Native doesn't have Node.js process.env at runtime, so values must be baked in.
const versionTs = `// Auto-generated by scripts/extract-version.cjs from .planning/STATE.md -- do not edit manually
/**
 * Lumio Version - Single Source of Truth
 *
 * This file is generated at build time by scripts/extract-version.cjs.
 * The version is extracted from .planning/STATE.md Milestone field.
 * Build metadata is baked in as string literals (React Native has no process.env).
 */
export const VERSION = "${version}";

/**
 * Build info baked in at generation time.
 * CI sets BUILD_NUMBER, GIT_SHA, BUILD_DATE env vars before running this script.
 * Local dev gets fallback values: "dev", "local", current timestamp.
 */
export const BUILD_INFO: {
  readonly version: string;
  readonly buildNumber: string;
  readonly gitSha: string;
  readonly buildDate: string;
} = {
  version: VERSION,
  buildNumber: "${buildNumber}",
  gitSha: "${gitSha}",
  buildDate: "${buildDate}",
};

export type BuildInfo = typeof BUILD_INFO;

/**
 * Formatted version string for display
 */
export function getVersionString(): string {
  return \`v\${BUILD_INFO.version}\`;
}

/**
 * Full version string for debug
 */
export function getFullVersionString(): string {
  return \`v\${BUILD_INFO.version} (\${BUILD_INFO.buildNumber}-\${BUILD_INFO.gitSha.slice(0, 7)})\`;
}

/**
 * Display version with build reference for app UI
 * Format: v1.7+42.abc1234 (CI) or v1.7+dev (local)
 */
export function getDisplayVersion(): string {
  if (BUILD_INFO.buildNumber === "dev") {
    return \`v\${BUILD_INFO.version}+dev\`;
  }
  return \`v\${BUILD_INFO.version}+\${BUILD_INFO.buildNumber}.\${BUILD_INFO.gitSha.slice(0, 7)}\`;
}
`;

fs.writeFileSync(VERSION_TS_PATH, versionTs, "utf-8");

// 5. Sync root package.json version
const packageJsonContent = fs.readFileSync(PACKAGE_JSON_PATH, "utf-8");
const packageJson = JSON.parse(packageJsonContent);
packageJson.version = version;
fs.writeFileSync(
  PACKAGE_JSON_PATH,
  JSON.stringify(packageJson, null, 2) + "\n",
  "utf-8"
);

// 6. Print version to stdout
console.log(version);
